### ISSUE TITLE
[2024-09-03] rejo_promotionA.py Feedback by merrong925

### ISSUE THREAD

**Issue by Mingguriguri** [r3j0/BiGStudy-SurvivalAlgorithm#2]
https://github.com/r3j0/BiGStudy-SurvivalAlgorithm/blob/54b0f6438fe9dadd4a2467934171dc49ded89f86/2024-09-1/promotionA/rejo_promotionA.py#L9-L11

### 👍잘 구현한 점
단순 if-else 부분을 저는 풀어서 적었는데 rejo님께서는 `삼항 연산자(if-else)`를 사용하여 조건에 따라 값을 처리하는 로직이 매우 간결해진 것 같습니다!

**Comment by r3j0** [comment]
피드백 감사합니다! :D
