### ISSUE TITLE
[2024-09-03] rejo_promotionB.py Feedback by merrong925

### ISSUE THREAD

**Issue by Mingguriguri** [r3j0/BiGStudy-SurvivalAlgorithm#3]
https://github.com/r3j0/BiGStudy-SurvivalAlgorithm/blob/54b0f6438fe9dadd4a2467934171dc49ded89f86/2024-09-1/promotionB/rejo_promotionB.py#L8-L20

### 👍잘 구현한 점/배울 점
- 저는 이 문제를 누적합으로 풀이를 했습니다. 그래서 누적합 방식으로 접근하면 매 구간마다 k개의 요소를 다시 합산하여 동일한 요소가 중복해서 합산이 되었는데, 
- 슬라이딩 윈도우 방식으로 접근하니 현재 구간의 합을 이전 구간의 합을 토대로 계산하여 불필요한 중복 계산 없이 더 효율적인 코드인 것 같습니다!

### 🧐개선하면 좋을 점
이미 충분합니다!

**Comment by r3j0** [comment]
피드백 감사합니다 :laughing: 문제의 제한이 작아서 단순히 브루트포싱해도 되지만, 슬라이딩 윈도우를 사용하면 더 적은 시간이 걸릴 것 같습니다!
