### ISSUE TITLE
[2024-09-05] rejo_promotionE.py Feedback by merrong925

### ISSUE THREAD

**Issue by Mingguriguri** [r3j0/BiGStudy-SurvivalAlgorithm#6]
https://github.com/r3j0/BiGStudy-SurvivalAlgorithm/blob/344117775abbd040faf4948770d1999a31405040/2024-09-1/promotionE/rejo_promotionE.py#L31-L37

### 👍잘 구현한 점/배울 점
- XOR 연산 사용한 방식은 배워갈 점인 것 같습니다! 흑, 백을 번갈아가는데에 적합하고 효율적인 것 같네요!
- 저는 방향 탐색을 일반 방식이랑 반대 방향 방식 두 개를 썼는데 굳이 두 방식을 쓰지 않아도 가능하다는 것을 알게되었습니다.

### 🧐개선하면 좋을 점
이미 충분합니다!
굳이 추가한다면, 백준에서 주어진 변수 외의 정보는 주석을 추가하면 더 직관적인 코드가 될 것 같습니다!

### ✨번외

**Comment by r3j0** [comment]
피드백 감사합니다. 의식의 흐름대로 코드를 짜고 제출한 대로 바로 올렸더니 주석을 좋게 못 달았던 것 같네요 :cry:
