### ISSUE TITLE
[2024-09-05] rejo_promotionC.py Feedback by merrong925

### ISSUE THREAD

**Issue by Mingguriguri** [r3j0/BiGStudy-SurvivalAlgorithm#7]
https://github.com/r3j0/BiGStudy-SurvivalAlgorithm/blob/344117775abbd040faf4948770d1999a31405040/2024-09-1/promotionC/rejo_promotionC.py#L6-L17

### 👍잘 구현한 점/배울 점
- n % 5의 값에 따라 발생할 수 있는 모든 경우를 잘 구분하여 처리하셨습니다! 이렇게도 접근할 수 있다는 점에 배워갑니다. 
- _(저도 어떻게든 규칙을 찾아보려고 했는데, 규칙을 찾지 못해서 반복문 쳐리를 했거든요....)_

### 🧐개선하면 좋을 점
- 너무 깔끔해서 충분한 것 같습니다!

**Comment by r3j0** [comment]
피드백 감사합니다!
