### ISSUE TITLE
[2024-09-05] rejo_promotionD.py Feedback by merrong925

### ISSUE THREAD

**Issue by Mingguriguri** [r3j0/BiGStudy-SurvivalAlgorithm#8]
https://github.com/r3j0/BiGStudy-SurvivalAlgorithm/blob/344117775abbd040faf4948770d1999a31405040/2024-09-1/promotionD/rejo_promotionD.py#L15-L20

### 👍잘 구현한 점/배울 점
n! 내에서 소수 a가 몇 번 곱해지는지 계산하는 방법을 명확하게 이해하고, 이를 효율적으로 구현하셨습니다. n을 a의 거듭제곱으로 나눈 몫을 반복적으로 더하여 최대의 k 값을 찾는 과정이 잘 구현되어 있습니다! 

### 🧐개선하면 좋을 점
개선할 사항 없이 좋은 코드인 것 같습니다!

**Comment by r3j0** [comment]
피드백 감사합니다! :laughing:
